Algoritmo "Questão 26"

Var
   x, resto : inteiro

Inicio
resto <- 5
      escreval("Números que divididos por 11 dão resto igual a 5")
      escreval("---------------------------------------------------")
  para x<-1000 ate 1999 faca
     se x%11 = resto entao
        escreval(x)
     fimse
  fimpara
  escreval("-----------------------------------------------------------")
  escreval("São esses!!!!")

Fimalgoritmo